### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by drnextgis** [sacrud/ps_alchemy#6]
I'm using pyramid_sacrud and get the folowing error when trying to edit table record which has cyrillic value. It looks like ps_alchemy issue:

```
Traceback (most recent call last):
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 209, in toolbar_tween
    response = _handler(request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 602, in __call__
    return view(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 497, in _class_view
    response = getattr(inst, attr)()
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/ps_alchemy/views.py", line 137, in edit_form_post_view
    for d in deserialized
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/ps_alchemy/views.py", line 138, in <dictcomp>
    for k, v in d.items()}
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/ps_alchemy/views.py", line 33, in preprocessing_value
    if not str(value).isdigit() and isinstance(
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by drnextgis** [comment]
Closed via https://github.com/sacrud/ps_alchemy/commit/ce42b2bcf51c67facd4032e7520a1154db1769b6

**Comment by uralbash** [comment]
@drnextgis Thank you very much, I've added a couple more tests
